const MAINPAGE_SEARCH_MODE = 'MAINPAGE_SEARCH_MODE';
const MAINPAGE_SAVED_MODE  = 'MAINPAGE_SAVED_MODE';
const MAINPAGE_TRANSACTION_MODE = 'MAINPAGE_TRANSACTION_MODE';
const MAINPAGE_SHARE_MODE  = 'MAINPAGE_SHARE_MODE';
const MAINPAGE_FEEDBACK_MODE = 'MAINPAGE_FEEDBACK_MODE';

module.exports = {
    MAINPAGE_SEARCH_MODE,
    MAINPAGE_SAVED_MODE,
    MAINPAGE_TRANSACTION_MODE,
    MAINPAGE_SHARE_MODE,
    MAINPAGE_FEEDBACK_MODE,
}