const REQUEST_SEND = 'REQUEST_SEND';
const REQUEST_CANCEL = 'REQUEST_CANCEL';
const REQUEST_TIMER_EXPIRED = 'REQUEST_TIMER_EXPIRED';
const REQUEST_ACCEPTED = 'REQUEST_ACCEPTED';
const REQUEST_REJECTED = 'REQUEST_REJECTED';

export {
    REQUEST_SEND,
    REQUEST_CANCEL,
    REQUEST_TIMER_EXPIRED,
    REQUEST_ACCEPTED,
    REQUEST_REJECTED
}