const TRANSACTION_LIVE_MODE = 'TRANSACTION_LIVE_MODE';
const TRANSACTION_SUCCESS_MODE = 'TRANSACTION_SUCCESS_MODE';
const TRANSACTION_CANCEL_MODE = 'TRANSACTION_CANCAL_MODE';
const TRANSACTION_TIME_EXPIRED_MODE = 'TRANSACTION_TIME_EXPIRED_MODE';

module.exports = {
    TRANSACTION_LIVE_MODE,
    TRANSACTION_SUCCESS_MODE,
    TRANSACTION_CANCEL_MODE,
    TRANSACTION_TIME_EXPIRED_MODE
}